### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by metainfa** [Deraen/frakkin-xkb#1]
Hi. 
Thank you for this program. 
I have custom layout with bluetooth keyboard, after unplug/plug keyboard X reset to default layout. I create udev rules to run script `RUN+="$HOME/load-my-custom-layout-auto.sh`. Script run OK, but layout don't loaded. I try various variants `sudo -u user env DISPLAY=:0 load-my-custom-layout-auto.sh`, research all internet but no success :-(  Run as `user` script work, as `sudo -u user` dont' work ...

Then i find you program ... work like charm :-)

**Comment by Deraen** [comment]
Thanks!
